# Namų darbai

## Namų darbai 4

In [2]:
# Rasti pasikartojančius elementus tarp dviejų list.

a = [1,2,3,4,5,6,7,8,9,15]
b = [3,8,9,11,15]
# Gauti rezultatą c = [3,8,9,15] nes šie skaičiai pasikartoja abiejuose list.

print( list( set(a).intersection(b) ) )

[8, 9, 3, 15]


In [4]:
# 2. Išfiltruoti unikalius teigiamus numerius iš sąrašo.

x = [1, 5, 1, 2, 8, -9, 10, 1, -8, -900, 14, 5, -8, 2, 1, -20, 900, 800, -6, -8, 12, 1]

positive_numbers = []
for number in set(x):
    if number > 0:
        positive_numbers.append(number)

print (positive_numbers)
positive_numbers_2 = [number for number in set(x) if number > 0]
print (positive_numbers_2)

[800, 1, 2, 900, 5, 8, 10, 12, 14]
[800, 1, 2, 900, 5, 8, 10, 12, 14]


In [5]:
# 3. Parašykite funkciją, kuri priims string tipo kintamąjį, gražinkite kiek tame string'ę yra raidžių, skaičių, skyrybos (specialių) ženklų ir tarpų.
# for loop kiekvienam simboliui string'e
# ar simbolis yra skaičius/raidė/tarpas/nei tas nei tas +=1
# gražinsime f stringą - “raidžiu yra: {raidziu_suma}…”

def text_extract(text: str):
    numbers = 0
    letters = 0
    spaces = 0
    specials = 0
    for symbol in text:
        if symbol.isalpha():
            letters += 1
        elif symbol.isdigit():
            numbers += 1
        elif symbol.isspace():
            spaces += 1
        else:
            specials +=1
    print (f'letters: {letters}, numbers: {numbers}, spaces: {spaces}, specials: {specials}')

text_extract("hello 148   !$%^#@^")

letters: 5, numbers: 3, spaces: 4, specials: 7


In [6]:
# 4. Parašyti funkciją, kuri priima vieną list tipo kintamąjį, funkcija grąžina skirtumą tarp didžiausio skaičiaus ir mažiausio skaičiaus.

def my_function(my_list):
    return max(my_list) - min(my_list)

my_function([1, 5, 6, 10, 4]) #->  9 ( nes 10 - 1)

9

In [11]:
def anomaly(*args):
    for i in range(len(args)-1):
        if args[i+1] == args[i]+1:
            print(f'Tarp skaiciu {args[i]} ir {args[i+1]} anomalijos nera')
        else:
            missing_numbers = ", ".join(str(e) for e in list(range(args[i]+1,args[i+1])))
            print(f'Anomalija yra! Skaiciai {args[i]} ir {args[i+1]} nera einantys vienas po kito! Trukstamas skaicius/skaiciai yra {missing_numbers}')
        # print(list(*args)[i])

In [22]:
anomaly(17,18,19,20,21, 25,26, 30)

Tarp skaiciu 17 ir 18 anomalijos nera
Tarp skaiciu 18 ir 19 anomalijos nera
Tarp skaiciu 19 ir 20 anomalijos nera
Tarp skaiciu 20 ir 21 anomalijos nera
Anomalija yra! Skaiciai 21 ir 25 nera einantys vienas po kito! Trukstamas skaicius/skaiciai yra 22, 23, 24
Tarp skaiciu 25 ir 26 anomalijos nera
Anomalija yra! Skaiciai 26 ir 30 nera einantys vienas po kito! Trukstamas skaicius/skaiciai yra 27, 28, 29


In [19]:
def anomaly_2( my_list):
    
    for left_number, right_number in zip(my_list[:-1], my_list[1:] ):
        # print (left_number, right_number)
        if left_number + 1 == right_number:
            print(f'Tarp skaiciu {left_number} ir {right_number} anomalijos nera')
        else:
            missing_numbers = ", ".join(str(e) for e in list(range(left_number+1,right_number)))
            print(f'Anomalija yra! Skaiciai {left_number} ir {right_number} nera einantys vienas po kito! Trukstamas skaicius/skaiciai yra {missing_numbers}')

In [23]:
my_list = [17,18,19,20,21,25,26,30]
print (my_list[:-1])
print (my_list[1:])
anomaly_2(my_list)

[17, 18, 19, 20, 21, 25, 26]
[18, 19, 20, 21, 25, 26, 30]
Tarp skaiciu 17 ir 18 anomalijos nera
Tarp skaiciu 18 ir 19 anomalijos nera
Tarp skaiciu 19 ir 20 anomalijos nera
Tarp skaiciu 20 ir 21 anomalijos nera
Anomalija yra! Skaiciai 21 ir 25 nera einantys vienas po kito! Trukstamas skaicius/skaiciai yra 22, 23, 24
Tarp skaiciu 25 ir 26 anomalijos nera
Anomalija yra! Skaiciai 26 ir 30 nera einantys vienas po kito! Trukstamas skaicius/skaiciai yra 27, 28, 29


In [25]:
# 6. Parašykite funkciją, kuri priims list’ą, gaukite didžiausią šalia esančių skaičių sandaugą.

my_list = [3, 6, 5, -5, 7, 3]

# rezultatas = 21, nes 7 ir 3 sandauga yra didžiausiadef anomaly_2( my_list):
def max_neighbors( my_list):
    max_value = my_list[0] * my_list[1]
    for left_number, right_number in zip(my_list[1:-1], my_list[2:] ):
        if left_number * right_number > max_value:
            max_value = left_number * right_number
    return max_value

max_neighbors(my_list)

30

## Namų darbai 3

In [26]:
# 1. Iš pirmų 100 skaičių, jeigu skaičius dalinasi iš 2 be liekanos, atspausdinkite ‘Fizz’,
# jeigu skaičius dalinasi iš 3 be liekanos atspausdinkite ‘Buzz’, jei skaičius dalinasi iš 2 ir 3 be liekanos, atspausdinkite ‘FizzBuzz’

for numbers in range(1, 101):
    if numbers %6 == 0:
        print(numbers, "FizzBuzz")
    elif numbers %3 == 0:
        print(numbers, "Buzz")
    elif numbers %2 == 0:
         print(numbers, "Fizz")

2 Fizz
3 Buzz
4 Fizz
6 FizzBuzz
8 Fizz
9 Buzz
10 Fizz
12 FizzBuzz
14 Fizz
15 Buzz
16 Fizz
18 FizzBuzz
20 Fizz
21 Buzz
22 Fizz
24 FizzBuzz
26 Fizz
27 Buzz
28 Fizz
30 FizzBuzz
32 Fizz
33 Buzz
34 Fizz
36 FizzBuzz
38 Fizz
39 Buzz
40 Fizz
42 FizzBuzz
44 Fizz
45 Buzz
46 Fizz
48 FizzBuzz
50 Fizz
51 Buzz
52 Fizz
54 FizzBuzz
56 Fizz
57 Buzz
58 Fizz
60 FizzBuzz
62 Fizz
63 Buzz
64 Fizz
66 FizzBuzz
68 Fizz
69 Buzz
70 Fizz
72 FizzBuzz
74 Fizz
75 Buzz
76 Fizz
78 FizzBuzz
80 Fizz
81 Buzz
82 Fizz
84 FizzBuzz
86 Fizz
87 Buzz
88 Fizz
90 FizzBuzz
92 Fizz
93 Buzz
94 Fizz
96 FizzBuzz
98 Fizz
99 Buzz
100 Fizz


In [31]:
for numbers in range(1, 101):
    result_text = ''
    if numbers %2 == 0:
        result_text += "Fizz"
        # result_text = result_text + 'Fizz'
    if numbers %3 == 0:
        result_text += "Buzz"
    print(numbers, result_text)
    

1 
2 Fizz
3 Buzz
4 Fizz
5 
6 FizzBuzz
7 
8 Fizz
9 Buzz
10 Fizz
11 
12 FizzBuzz
13 
14 Fizz
15 Buzz
16 Fizz
17 
18 FizzBuzz
19 
20 Fizz
21 Buzz
22 Fizz
23 
24 FizzBuzz
25 
26 Fizz
27 Buzz
28 Fizz
29 
30 FizzBuzz
31 
32 Fizz
33 Buzz
34 Fizz
35 
36 FizzBuzz
37 
38 Fizz
39 Buzz
40 Fizz
41 
42 FizzBuzz
43 
44 Fizz
45 Buzz
46 Fizz
47 
48 FizzBuzz
49 
50 Fizz
51 Buzz
52 Fizz
53 
54 FizzBuzz
55 
56 Fizz
57 Buzz
58 Fizz
59 
60 FizzBuzz
61 
62 Fizz
63 Buzz
64 Fizz
65 
66 FizzBuzz
67 
68 Fizz
69 Buzz
70 Fizz
71 
72 FizzBuzz
73 
74 Fizz
75 Buzz
76 Fizz
77 
78 FizzBuzz
79 
80 Fizz
81 Buzz
82 Fizz
83 
84 FizzBuzz
85 
86 Fizz
87 Buzz
88 Fizz
89 
90 FizzBuzz
91 
92 Fizz
93 Buzz
94 Fizz
95 
96 FizzBuzz
97 
98 Fizz
99 Buzz
100 Fizz


In [33]:
# 2. Leiskite vartotojui pasirinkti skaičių, jeigu įvestas skaičius yra daugiau arba lygus 10, atspausdinkite visus skaičius kurie dalinasi iš 5 su liekana.
# Kitu atveju nieko nedaryti ir pranešti vartotojui apie tai.
input_number = int( input('Iveskite skaiciu: ') )
print (f'Ivestas skaicius {input_number}')
numbers = list(range(1,input_number+1) )
if input_number >= 10:
    liekana = []
    for number in numbers:
        if number % 5 != 0:
            liekana.append(number)
    print(liekana)
else:
    print("Skaicius mazesnis arba lygus 10")

Ivestas skaicius 17
[1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 16, 17]


In [39]:
# 3. sudarykite visas įmanomas kombinacijas iš pateiktų 3 list'ų. Kiek yra iš viso kombinacijų?
# Išrikiuokite kombinacijų sąrašą nuo didžiausios iki mažiausios reikšmės (Gali tekti paieškoti informacijos kaip tai padaryti).
a = ['1','2','3','4','5']
b = ['labas', 'vakaras', 'kokia grazi diena', 'siandien uz lango', '10 laipsniu silumos']
c = ['100', '200', 40, 10]

# kombinacijos = []
# for x in a:
#     for y in b:
#         for z in c:
#             kombinacijos.append( (x,y,z) )
# print (kombinacijos)
kombinacijos = [ (x,y, int(z) ) for x in a for y in b for z in c ]

print (sorted(kombinacijos, key=lambda x: x[2], reverse=True ) )
print ('\n\n')
print (sorted(kombinacijos, key=lambda x: x[0], reverse=True ) )
# print (kombinacijos)

[('1', 'labas', 200), ('1', 'vakaras', 200), ('1', 'kokia grazi diena', 200), ('1', 'siandien uz lango', 200), ('1', '10 laipsniu silumos', 200), ('2', 'labas', 200), ('2', 'vakaras', 200), ('2', 'kokia grazi diena', 200), ('2', 'siandien uz lango', 200), ('2', '10 laipsniu silumos', 200), ('3', 'labas', 200), ('3', 'vakaras', 200), ('3', 'kokia grazi diena', 200), ('3', 'siandien uz lango', 200), ('3', '10 laipsniu silumos', 200), ('4', 'labas', 200), ('4', 'vakaras', 200), ('4', 'kokia grazi diena', 200), ('4', 'siandien uz lango', 200), ('4', '10 laipsniu silumos', 200), ('5', 'labas', 200), ('5', 'vakaras', 200), ('5', 'kokia grazi diena', 200), ('5', 'siandien uz lango', 200), ('5', '10 laipsniu silumos', 200), ('1', 'labas', 100), ('1', 'vakaras', 100), ('1', 'kokia grazi diena', 100), ('1', 'siandien uz lango', 100), ('1', '10 laipsniu silumos', 100), ('2', 'labas', 100), ('2', 'vakaras', 100), ('2', 'kokia grazi diena', 100), ('2', 'siandien uz lango', 100), ('2', '10 laipsniu 

In [40]:
from operator import itemgetter
sorted_kombinacijos = sorted(kombinacijos, key= itemgetter(0), reverse= True)

print(sorted_kombinacijos)

[('5', 'labas', 100), ('5', 'labas', 200), ('5', 'labas', 40), ('5', 'labas', 10), ('5', 'vakaras', 100), ('5', 'vakaras', 200), ('5', 'vakaras', 40), ('5', 'vakaras', 10), ('5', 'kokia grazi diena', 100), ('5', 'kokia grazi diena', 200), ('5', 'kokia grazi diena', 40), ('5', 'kokia grazi diena', 10), ('5', 'siandien uz lango', 100), ('5', 'siandien uz lango', 200), ('5', 'siandien uz lango', 40), ('5', 'siandien uz lango', 10), ('5', '10 laipsniu silumos', 100), ('5', '10 laipsniu silumos', 200), ('5', '10 laipsniu silumos', 40), ('5', '10 laipsniu silumos', 10), ('4', 'labas', 100), ('4', 'labas', 200), ('4', 'labas', 40), ('4', 'labas', 10), ('4', 'vakaras', 100), ('4', 'vakaras', 200), ('4', 'vakaras', 40), ('4', 'vakaras', 10), ('4', 'kokia grazi diena', 100), ('4', 'kokia grazi diena', 200), ('4', 'kokia grazi diena', 40), ('4', 'kokia grazi diena', 10), ('4', 'siandien uz lango', 100), ('4', 'siandien uz lango', 200), ('4', 'siandien uz lango', 40), ('4', 'siandien uz lango', 10

In [43]:
# 4. Paskaičiuoti pelną pardavus visas prekes. Informacija apie kainą ir kiekius yra pateikiama  kaip dictionary, atsakymą suapvalinti iki 2 skaičių po kablelio.
x = { "cost_price": 32.67,
         "sell_price": 45.00,
         "inventory": 1212 }

pelnas = (x['sell_price'] - x['cost_price']) * x['inventory']

print( f'pelnas: {round(pelnas, 2)}')
print( f'pelnas: {pelnas:.2f}')


pelnas: 14943.96
pelnas: 14943.96


# Numpy

In [44]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\Robotux\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [52]:
a_list = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]
print (a_list)
print (a_list[1][1])
print ( [ row[1] for row in a_list])

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
6
[2, 6, 10]


In [45]:
import numpy as np

## 2D array

In [59]:
a_np = np.array( [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ]
)
print (a_np)
print(type(a_np))
print( a_np[1][1] )
print( a_np[1, 1] ) # row index, column index
print ('\n')
print( a_np[:, 1] )
print ('\n')
print( a_np[:2, 1] )
print ('\n')
print( a_np[:2, 1:3] )

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
6
6


[ 2  6 10]


[2 6]


[[2 3]
 [6 7]]


In [69]:
print(a_np.shape)
print(len(a_np))

(3, 4)
3


## 1D array

In [66]:
array_1d = np.array( [1,5,7,9,71,14] )

In [68]:
print (array_1d.shape)
print (len(array_1d) )

(6,)
6


In [70]:
print (array_1d)

[ 1  5  7  9 71 14]


## 3D array

In [72]:
arr_3d = np.array([
        [ 
            [1, 2, 3], 
            [4, 5, 6]
        ],
        [
            [1, 2, 3],
            [4, 5, 6]
        ]
    ]
)


In [73]:
print (arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [74]:
print (arr_3d.shape)

(2, 2, 3)


In [80]:
n_dim_array = np.random.randn(2,5,3,4,4,4,4)
print (n_dim_array.shape)
print (n_dim_array)

(2, 5, 3, 4, 4, 4, 4)
[[[[[[[ 6.33316741e-01 -1.58766424e-01  7.24429241e-01
       -5.84691930e-01]
      [-7.61277176e-01 -9.60508021e-01  1.69108527e-01
       -1.27959104e+00]
      [-3.61090202e-01  9.02134064e-01 -6.43965841e-01
       -1.24550709e+00]
      [ 1.33852423e-01  5.27565502e-01  2.01686030e-01
       -4.56670281e-01]]

     [[-1.00312927e+00  1.45774000e+00  1.40449395e-01
        1.24804313e+00]
      [ 2.73254769e-01 -1.59117421e-01 -9.54763575e-01
        5.08130511e-02]
      [-1.66329997e+00 -3.72885268e-01  4.97384029e-02
        1.56327826e+00]
      [-6.13377644e-01  8.55616476e-01 -1.32600868e-01
       -8.38589871e-01]]

     [[ 1.44735476e+00  1.61716713e-01 -1.64768489e-01
        1.39269230e+00]
      [ 3.03604593e-01 -2.72531245e+00 -1.06650146e+00
       -5.28243851e-01]
      [-1.84873903e-01 -6.33561349e-01 -1.81573655e+00
        2.72745255e-01]
      [-2.04208297e+00 -1.36656739e+00  1.56220833e+00
        1.41967992e+00]]

     [[-1.25824612e-02  

## Numpy operations

In [81]:
py_list = [1,2,3,4,5]
print (py_list * 3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [82]:
np_array = np.array( [1,2,3,4,5] )


In [83]:
print (np_array * 3)

[ 3  6  9 12 15]


In [84]:
print (np_array / 3)

[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [86]:
print (np_array ** 3)

[  1   8  27  64 125]


In [87]:
print (py_list)

[1, 2, 3, 4, 5]


In [88]:
py_list[2:4] = 100

TypeError: can only assign an iterable

In [92]:
np_array[2:4] = 100
print (np_array)
np_array[2:4] = [100, 200]
print (np_array)
# np_array[2:4] = [100, 200, 300] # wrong shapes

[  1   2 100 100   5]
[  1   2 100 200   5]


ValueError: could not broadcast input array from shape (3,) into shape (2,)

## Numpy speed

In [ ]:
# np.core.records.array

In [62]:
size = 100000

In [93]:
py_list = list(range(size))

In [95]:
np_arr = np.arange(size)

In [98]:
%%timeit # Jupyter command

list_rez = []
for number in py_list:
    list_rez.append( number * 10 )

3.65 ms ± 63.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [99]:
%%timeit # Jupyter command

np_rez = np_arr * 10

45 µs ± 381 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Reshape

In [102]:
np_array = np.arange(0,100,2)
print (np_array)
print(np_array.shape)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
(50,)


In [103]:
print (np_array.reshape( (5,10) ) )

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]


In [112]:
print (np_array.reshape( (1,10,5) ) )

[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]
  [30 32 34 36 38]
  [40 42 44 46 48]
  [50 52 54 56 58]
  [60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]
  [90 92 94 96 98]]]


In [113]:
print (np_array.reshape( (2,1,-1) ) ) # 

[[[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44
   46 48]]

 [[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
   96 98]]]


In [119]:
array_2d = np.array( [ [1,2], [4,3], [7,4] ] )
print ('2D\n',array_2d)
print( array_2d.shape)
array_3d = np.array( [
    [ [1,2], [4,3], [7,4] ],
    [ [2,2], [4,3], [7,4] ],
    [ [3,2], [4,3], [7,4] ],
    [ [4,2], [4,3], [7,4] ],
]
)
print ('3D\n',array_3d)
print( array_3d.shape)

2D
 [[1 2]
 [4 3]
 [7 4]]
(3, 2)
3D
 [[[1 2]
  [4 3]
  [7 4]]

 [[2 2]
  [4 3]
  [7 4]]

 [[3 2]
  [4 3]
  [7 4]]

 [[4 2]
  [4 3]
  [7 4]]]
(4, 3, 2)


## Numpy methods

In [120]:
np.mean(array_3d)

3.75

In [125]:
np.mean(array_3d, axis=2)

array([[1.5, 3.5, 5.5],
       [2. , 3.5, 5.5],
       [2.5, 3.5, 5.5],
       [3. , 3.5, 5.5]])

In [128]:
print (array_2d)
print ('Column mean', np.mean(array_2d, axis=0) )
print ('Row mean', np.mean(array_2d, axis=1))

[[1 2]
 [4 3]
 [7 4]]
Column mean [4. 3.]
Row mean [1.5 3.5 5.5]


In [130]:
np.std(array_2d)

1.8929694486000912

In [131]:

print ('Column std', np.std(array_2d, axis=0) )

Column std [2.44948974 0.81649658]


In [132]:
np.sum(array_2d)
print ('Column sum', np.sum(array_2d, axis=0) )
print ('Row sum', np.sum(array_2d, axis=1) )

Column sum [12  9]
Row sum [ 3  7 11]


In [133]:
array_2d.transpose()

array([[1, 4, 7],
       [2, 3, 4]])

In [134]:
array_2d.T

array([[1, 4, 7],
       [2, 3, 4]])

## Comparisons

In [136]:
np_array = np.arange(0,60,2)
print (np_array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58]


In [137]:
np_array[ np_array < 30 ]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [138]:
np_array < 30 # also called mask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [139]:
np_array[ np_array % 3 == 0 ]

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54])